### PR TITLE
File author -> File authors

### LINKED ISSUE #57: Should the file-author be allowed to have multiple authors?
### PyKED/ChemKED version
v0.1.5

Title question raised by Mike Burke's group at Columbia.

### PR DESCRIPTION
**Pull request by bryanwweber**
- [x] Fixes #57.
- [x] Tests added
- [x] Added entry into `CHANGELOG.md`

Changes proposed in this pull request:
 - Change `file-author` field to a list called `file-authors`

Changes contributed by @kypore1 aka @EthanBesse

@pr-omethe-us/chemked

### CODE REVIEW

**Comment by kyleniemeyer** [comment]
We're missing some coverage `converters.py`!

**Comment by bryanwweber** [comment]
I've got it _covered_ in a PR that requires this one 😸

**Comment by kyleniemeyer** [comment]
Hah, ok

**Comment by kyleniemeyer** [comment]
Wow, interestingly, “Pulk requests that have a failing status can’t be merged on a phone.”

I tried.

**Comment by bryanwweber** [comment]
Bogus! Well, I can merge when I get a chance, or you can take care of it if I don't get it 😁

**Pull request merged**
