### PR TITLE
Import the __version__ attribute to the top-level module

### LINKED ISSUE #98: pyked._version.__version__ should be pyked.__version__
```
$ pyked.__version__
AttributeError: module 'pyked' has no attribute '__version__'
$ pyked._version.__version__
'0.3.0'
```

### PR DESCRIPTION
**Pull request by bryanwweber**
- [x] Fixes #98
- [x] Added entry into `CHANGELOG.md`

Changes proposed in this pull request:
- Add the ability to import the `__version__` attribute from the `_version` module at the top-level of the package

```python
from pyked import __version__
print(__version__)
```

@pr-omethe-us/chemked

### CODE REVIEW

**Comment by kyleniemeyer** [comment]
@bryanwweber this looks fine to me, but the AppVeyor build failed for some reason...

**Comment by bryanwweber** [comment]
Looks like it failed because one of the expected `ResourceWarnings` didn't show up. We might need to loosen the criteria on that test... or perhaps figure out a way to fix Habanero so it doesn't do that (I think its Habanero, anyways). I restarted the build, let's see what happens

**Comment by bryanwweber** [comment]
Well, I don't know why the tests are failing, but it's not actually a problem with the code itself, its a problem with the test. Do you want to merge, or do you want me to try to fix it?

**Comment by kyleniemeyer** [comment]
I wonder if this is another package version issue?

**Comment by kyleniemeyer** [comment]
We probably need to try and fix this, because I don't think we'll have an updated Windows package until we do.

**Comment by kyleniemeyer** [comment]
Welp, I don't think it's a habanero version issue, because it looks like 0.6.0 in both the Windows and Linux test logs.

**Comment by kyleniemeyer** [comment]
I wonder if it's an issue with pytest, not habanero...

Here's the first failing test:
```
____________________ TestGetReference.test_valid_reference ____________________
self = <pyked.tests.test_converters.TestGetReference object at 0x000000604E661B38>
    def test_valid_reference(self):
        """Ensure valid reference reads properly.
            """
        root = etree.Element('experiment')
        ref = etree.SubElement(root, 'bibliographyLink')
    
        ref.set('doi', '10.1016/j.ijhydene.2007.04.008')
        ref.set('preferredKey', 'Chaumeix, N., Pichon, S., Lafosse, F., Paillard, C.-E., '
                'International Journal of Hydrogen Energy, 2007, (32) 2216-2226, '
                'Fig. 12., right, open diamond'
                )
    
        with pytest.warns(UserWarning) as w:
            ref = get_reference(root)
>       assert w[1].message.args[0] == ('Using DOI to obtain reference information, '
                                        'rather than preferredKey.'
                                        )
pyked\tests\test_converters.py:145: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = WarningsChecker(record=True), i = 1
    def __getitem__(self, i):
        """Get a recorded warning by index."""
>       return self._list[i]
E       IndexError: list index out of range
C:\Miniconda36-x64\envs\py3.5\lib\site-packages\_pytest\recwarn.py:139: IndexError

```

That last bit is kinda weird, no?

**Comment by bryanwweber** [comment]
Alright, I'll try to dig into this over the holiday.

**Comment by bryanwweber** [comment]
The issue is with Habanero, and more specifically, that they use the Requests library which leads to a bunch of ResourceWarnings. Apparently (based on these results), how all that gets handled is different on Windows vs. *nix. Anyhow, I've updated how we handle the warnings in the test suite so it should hopefully be cross platform now.

**Comment by bryanwweber** [comment]
All passed, LGTM.

**Pull request merged**
