### PR TITLE
Add ignition type

### LINKED ISSUE #34: DataPoint should provide information about how ignition detected
`DataPoint` objects currently do not contain information about how ignition is detected. This should be given, for example via an `ignition_type` attribute.

### PR DESCRIPTION
**Pull request by kyleniemeyer**
- [x] Fixes #34 .
- [x] Tests added to `test_datapoints()`

Changes proposed in this pull request:
 - Add ignition_type attribute to `DataPoint`, with test
 - Add tests and package data to `setup.py`

@pr-omethe-us/chemked

### CODE REVIEW

**Comment by kyleniemeyer** [comment]
OK, that failure is not actually a test failure, but something with `ruamel.yaml`, and only in the Python 3.5 build... 
screen shot 2017-02-27 at 1 08 58 am

**Comment by bryanwweber** [comment]
It seems like the failure is due to pylint... does it work for you locally?

**Comment by kyleniemeyer** [comment]
I get the same error locally (this is what I get for running the `pytest` test suite, but not `pylint`...).

Apparently this is a `pylint`/`ruamel.yaml` conflict: https://bugs.launchpad.net/ubuntu/+source/pylint/+bug/1651098

You can recreate by simply doing:

    echo "import ruamel.yaml" > test.py
    pylint --reports=no test.py

**Comment by bryanwweber** [comment]
The failure now is because of 2 things:

1. the DOI check for the reference in the new test is failing with the wrong year
2. there's a bug in how the `common-properties` are implemented. I filed #36 to address this

**Comment by bryanwweber** [comment]
Awesome, once we merge the uncertainties, we just need to make sure the pressure gets an uncertainty in `common-properties` too

**Pull request merged**
