### PR TITLE
made test_incorrect_doi_period_at_end test match description

### PR DESCRIPTION
**Pull request by kyleniemeyer**
- [X] Tests fixed: `test_incorrect_doi_period_at_end`
- [x] Added entry into `CHANGELOG.md`

Changes proposed in this pull request:
 - Makes test `test_incorrect_doi_period_at_end` match description

@pr-omethe-us/chemked

### CODE REVIEW

**Comment by bryanwweber** [comment]
Do we need this test? What is it testing for?

**Comment by kyleniemeyer** [comment]
If I recall, some of the ReSpecTh files I saw had periods at the end, and some didn't—so this was just a little test to make sure we can handle that.

**Comment by bryanwweber** [comment]
But a period at the end of a DOI is a different DOI, no? So if they have a period at the end, its automatically an invalid DOI regardless of why it has a period at the end, unless that period is meant to be stripped off in the processing?

**Comment by kyleniemeyer** [comment]
Ohh I just figured out/remembered what this test was for... it wasn't about a period at the end of the DOI, but at the end of the reference. 

In the case of an invalid reference, the converter puts whatever is given in the `detail` field in our `reference` (with a message so the user can manually correct). The period issue is minor, but a sentence is added after the reference data is copied, so the code checks for a period and adds if there isn't one. This was testing the other branch of that if statement, I think.

**Comment by bryanwweber** [comment]
OK that makes more sense. I rebased so its just one commit to avoid the noise and churn. Merged!

**Pull request closed without merging**
