### PR TITLE
Fix ORCID API calls

### PR DESCRIPTION
**Pull request by bryanwweber**
- [x] Added entry into `CHANGELOG.md`
- [x] Documentation updated

Changes proposed in this pull request:
- Replace the python-orcid package because it doesn't support the new ORCID API

@pr-omethe-us/chemked

### CODE REVIEW

**Comment by kyleniemeyer** [comment]
Do we need some tests for the new function?

**Comment by bryanwweber** [comment]
No, it should all be covered by the existing test suite

**Comment by kyleniemeyer** [comment]
CHANGELOG?

**Comment by kyleniemeyer** [comment]
I'm good with this other than that change.

**Comment by bryanwweber** [comment]
In #110

**Pull request merged**
